# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfp', '0002_auto_20170321_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='authExpireTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='authToken',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='refreshToken',
            field=models.TextField(null=True),
        ),
    ]
