# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfp', '0004_auto_20170322_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='authExpireTime',
            new_name='accessExpireTime',
        ),
    ]
