# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfp', '0005_auto_20170322_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='calendarId',
            field=models.TextField(null=True),
        ),
    ]
